apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
  name: cruiser-instance
  labels:
    description: Cruiser
    model: cruiser
spec:
  deviceModelRef:
    name: cruiser
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - edge-pi
status:
  twins:
    - propertyName: power-status
      desired:
        metadata:
          type: string
        value: 'ON'
